export const GET_HEALTHCARE_PROVIDER_DATA = "GET_PROVIDER_DATA"
export const GET_HEALTHCARE_PROVIDER_DATA_SUCCES = "GET_PROVIDER_DATA"
export const GET_HEALTHCARE_PROVIDER_DATA_FAILED = "GET_PROVIDER_DATA"

export const GET_PATIENT_DATA = "GET_PATIENT_DATA"
export const GET_PATIENT_SUCCESS= "GET_PATIENT_SUCCESS"
export const GET_PATIENT_FAILED = "GET_PATIENT_FAILED"